### PR TITLE
quickphrase/dict: Import Emoji 15.0 characters

### PR DESCRIPTION
**Pull request by mochaaP**
Add emoji data from Emoji 15.0.
Data derived from <https://github.com/github/gemoji>.

To generate this list, use the following snippet:

```bash
curl https://github.com/github/gemoji/raw/master/db/emoji.json -L | jq '.[] | (.aliases | map(":"+.+":"))[] + " " + .emoji' --raw-output > emoji-eac.mb
```

---

Copyright © 1991-2023 Unicode, Inc. All rights reserved.
<https://www.unicode.org/license.txt>

Copyright (c) 2019 GitHub, Inc. under the MIT License.
<https://github.com/github/gemoji/blob/master/LICENSE>

### CODE REVIEW

**Comment by CoelacanthusHex** [comment]
可惜没有中文版本的映射表，否则 fcitx5-chinese-addons 那边还有一个拼音版本的 emoji 字典可以更新。

**Comment by mochaaP** [comment]
估計 RIME 社區那邊有人做數據了，我找找看

**Comment by mochaaP** [comment]
@CoelacanthusHex <https://github.com/rime/rime-emoji/blob/master/opencc/emoji_word.txt>

這有一個。

**Comment by mochaaP** [comment]
Rebased

**Pull request merged**
