### PR TITLE
fix fcitx5-diagnose requests environment variables to be set to fcitx…

### PR DESCRIPTION
**Pull request by marguerite**
… instead of fcitx5

### CODE REVIEW

**Comment by wengxt** [comment]
this is intended.

**Comment by marguerite** [comment]
intended to use XMODIFIERS=@im=fcitx, GTK_IM_MODULE=fcitx and QT_IM_MODULE=fcitx? does fcitx5 recognize it?

**Comment by wengxt** [comment]
recognize it since the very first day

**Comment by marguerite** [comment]
does fcitx5 recognize both fcitx and fcitx5? I mean, if so, I can add something to the script to make it not complain and mislead

**Comment by naokiri** [comment]
What made you think it should be "fcitx5" instead of "fcitx"?
As far as I know fcitx5 never expected it to be "fcitx5".
Also even for distribution's modification, AFAIK Ubuntu 22.04 never used or expected "fcitx5" as those modifiers. Maybe there's some other distribution did their own modification, then you should report a PR on their packaging.

**Comment by marguerite** [comment]
I am the openSUSE packager, I used XMODIFIERS=@im=fcitx5 for a long time and my input method works like a charm...I even implement some systemd generators to distinguish fcitx and fcitx5 during start (I need to know if the user still uses fcitx to prompt a reminder for migration)...so I think that MODIFIER may also work since the very first day.

And if that's a mistake, I need to tweak my codes. so, you know, I need a guaranteed answer :-D

**Comment by marguerite** [comment]
okay, I'll steadily move back to fcitx.

**Pull request closed without merging**
