### PR TITLE
Optimize code

### PR DESCRIPTION
**Pull request by hantengc**
1. optimize icon acquisition logic to prepare for customizing icons for other desktop environments in the future

### CODE REVIEW

**Comment by CoelacanthusHex** [comment]
Shouldn't this thing be controlled by modifying the `input-keyboard` icon in the icon pack?

**Comment by hantengc** [comment]
@CoelacanthusHex 1. Not sure if there are any other packages that use the input-keyboard icon, changing the system icon name will have other effects
2. In the past, I used to use icons for the KDE environment, but I think I could add icons for other desktops as well

**Comment by wengxt** [comment]
I'm not sure if english us is the icon you want.

When this icon is used, it doesnt have to be English US

**Comment by hantengc** [comment]
@wengxt It means that other layout input methods are also using this icon, right? Then I should have our UI designers design a more generic icon

**Pull request closed without merging**
